### ISSUE TITLE
Need to clarify instructions - errors on install

### ISSUE THREAD

**Issue by remotesynth** [themefisher/liva-hugo#1]
I tried testing this theme out but ran into a ton of issues. Part of this is due to some lack of detail on the instructions but also just general issues.

1. Your installation instructions seem to leave out a number of important details. First, that you need to modify the Hugo config.toml to include `theme="liva-hugo`.
2. There appears to be a need to add a Google maps property to the site but no detail on what is required is shared.
3. I get a bunch of errors when the site loads and even removing the Google maps script loading didn't clear the errors. There were images that didn't load and a missing jQuery as far as I can tell. (Note: the second error below relates to #2 above as without setting this property, it tries to load the home page as a script).

```
(index):117 GET http://localhost:1313/images/ad.png 404 (Not Found)
(index):1 Uncaught SyntaxError: Unexpected token '<'
script.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at script.min.js:1
```

**Comment by Somrat37** [comment]
@remotesynth 

Thaks for your concern, i think your issue has been solved now, please pull the latest code
