### ISSUE TITLE
Integrity attribute on link-tag is empty

### ISSUE THREAD

**Issue by Frank3K** [themefisher/liva-hugo#10]
As can be seen on the [demo site](http://demo.themefisher.com/liva-hugo/) the integrity attribute of the link tag (of the style sheet) remains empty.

**Comment by Somrat37** [comment]
I think this is not an issue.

**Comment by Frank3K** [comment]
It works fine without the integrity value, but it would be better if it was set (otherwise the attribute itself could be left off). I'll look into it later this week.

**Comment by Somrat37** [comment]
This issue has been fixed
