### ISSUE TITLE
Slick settings

### ISSUE THREAD

**Issue by contributorpw** [themefisher/liva-hugo#14]
Hi!

1. The slick's plugin is awful on mobile. It should be more clear and not block the slide down.
1. Slick-dots is very thin.

Is there any chance that you will open access to the slick settings?

**Comment by Somrat37** [comment]
@contributorpw ,
i did some modification of this template, please download the latest code. hope you like it.

**Comment by contributorpw** [comment]
@Somrat37 Thank you!
