### ISSUE TITLE
Storing data from website

### ISSUE THREAD

**Issue by luisotavio88** [themefisher/liva-hugo#17]
Hi!

Liva-hugo demonstration has some input fields. Such as a contact form or a newsletter subscription. Where would this data be stored? 

Can I set my Mysql Database?

I will run it from R. 

Thanks

Luis

**Comment by themefisherDev** [comment]
@luisotavio88 ,

Contact from is working with https://formspree.io and newsletter subscription works with https://mailchimp.com

**Comment by luisotavio88** [comment]
@themefisherDev  Sorry, but I didn't find them in the code... Where should I go to sync them?

Is not possible to use my own DB?

Thanks

**Comment by themefisherDev** [comment]
You can add your won database, if you have knowledge about it.
