### ISSUE TITLE
Difficulties seeing Posts due to Date - LIVA Hugo Template

### ISSUE THREAD

**Issue by magoley** [themefisher/liva-hugo#20]
I currently working on relaunching our website for our private podcast using Hugo with you LIVA template.

my trouble is: posts are not showing up if I change the date in the front matter to to current dates. My suggestion is that somewhere in a config or list file the website thinks that 2020 dates are in the future and therefor not to be displayed.

Where do I find this config?

Thanks in Advance
Chris

**Comment by Somrat37** [comment]
Hey, there is no config like this. I suggest you to not change the date. you can create a new post for get a recent date. thanks

**Comment by magoley** [comment]
OK,

but since I am going to relaunch an already existing website with 
existing post, I need to make changes to the date.

And also I did create new posts and they did not apear on the start 
page.
So something might be wrong with the range oder list layout 
configurations.

What do you advise for me to do in order to see posts that do not 
contain the dates fron the sample content?

Thanks for your help.

Chris

Am 06.04.2020 05:41, schrieb Somrat:
