### ISSUE TITLE
Hugo Rendering Message "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by magoley** [themefisher/liva-hugo#21]
First of, yesterday "hugo server" was working for my new website that I build based on your liva template (awesome work BTW).

But I was running hugo from a download sub directory and after cleaning my download I had to get a new hugo for my WIN 10 OS.
Therefor I fetched myself a brand new hugo win 64 ext. (since the used liva template needs the extended hugo version for CSS). And also install git brand new to my PC.

And I changed taxonomy entries in my blog-posts. Since I found an issue (https://github.com/gohugoio/hugo/issues/7061) around taxonomy in the Hugo Community, I thought that be worth mentioning. 

Who can help reading the error messages (see below) to get my website rendering again? Many Thanks.

Executing:
“hugo server”

This is the result (I switched “.” to “(dot” so that it is not counted as a link):

Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xfdedb9]

goroutine 83 [running]:
github(dot)com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc0000d1800, 0x1, 0x0, 0xc000723ae0, 0x1, 0x1, 0x1aea8e0)
/root/project/hugo/hugolib/shortcode.go:505 +0x889
github(dot)com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc000731bf0, 0xc00073e780, 0xc000891400, 0xc00073f940, 0x23f4880)
/root/project/hugo/hugolib/page.go:783 +0xb87
github(dot)com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc00005b8e0, 0xc000ad2840, 0xc00073e780, 0x0, 0x0, 0x0, 0x0)
/root/project/hugo/hugolib/content_map_page.go:164 +0x62c
github(dot)com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc0007a8ed0, 0x2a, 0x1bb6880, 0xc000ad2840, 0xc00088bd00)
/root/project/hugo/hugolib/content_map_page.go:358 +0x157
github(dot)com/armon/go-radix.recursiveWalk(0xc000ad28a0, 0xc00088be10, 0xc07f00)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf7
github(dot)com/armon/go-radix.recursiveWalk(0xc000ad2870, 0xc00088be10, 0xfb7a69)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.recursiveWalk(0xc0009c2090, 0xc00088be10, 0x0)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.recursiveWalk(0xc00097d920, 0xc00088be10, 0x0)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.(*Tree).Walk(…)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github(dot)com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc00005b8e0, 0x0, 0x0)
/root/project/hugo/hugolib/content_map_page.go:331 +0xf3
github(dot)com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc00005b8e0, 0xc0004db2a0, 0xc00008bf00)
/root/project/hugo/hugolib/content_map_page.go:721 +0x6f
github(dot)com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0xc0004db2a0, 0xc00008bf68)
/root/project/hugo/hugolib/content_map_page.go:788 +0x35
github(dot)com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc0004db298, 0x0)
/root/project/hugo/common/para/para.go:52 +0x36
golang(dot)org/x/sync/errgroup.(*Group).Go.func1(0xc0007308d0, 0xc00073e0a0)
/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x6d
panic: runtime error: index out of range [0] with length 0

goroutine 48 [running]:
github(dot)com/gohugoio/hugo/hugolib.(*pageState).shiftToOutputFormat(0xc000731bf0, 0x401, 0x0, 0x0, 0x0)
/root/project/hugo/hugolib/page.go:916 +0x35e
github(dot)com/gohugoio/hugo/hugolib.(*pageState).initOutputFormat(…)
/root/project/hugo/hugolib/page.go:474
github(dot)com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender.func1(0xc000731bf0, 0x3209ff00)
/root/project/hugo/hugolib/hugo_sites.go:754 +0x50
github(dot)com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage.func1(0xc0007a8ed0, 0x2a, 0xc000ad2840, 0x2030000)
/root/project/hugo/hugolib/content_map_page.go:696 +0x3e
github(dot)com/gohugoio/hugo/hugolib.contentTrees.Walk.func1(0xc0007a8ed0, 0x2a, 0x1bb6880, 0xc000ad2840, 0x41a100)
/root/project/hugo/hugolib/content_map.go:851 +0x5b
github(dot)com/armon/go-radix.recursiveWalk(0xc000ad28a0, 0xc0007219c0, 0x0)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf7
github(dot)com/armon/go-radix.recursiveWalk(0xc000ad2870, 0xc0007219c0, 0xa)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.recursiveWalk(0xc0009c2090, 0xc0007219c0, 0x23966ce)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.recursiveWalk(0xc00097d920, 0xc0007219c0, 0xc8)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github(dot)com/armon/go-radix.(*Tree).Walk(…)
/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github(dot)com/gohugoio/hugo/hugolib.contentTrees.Walk(0xc0005a23a0, 0x4, 0x4, 0xc000721a00)
/root/project/hugo/hugolib/content_map.go:849 +0x6e
github(dot)com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage(0xc00005b8e0, 0xc000721a40)
/root/project/hugo/hugolib/content_map_page.go:694 +0x74
github(dot)com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender(0xc00012ab40, 0xc0009c8701, 0x0, 0x3, 0xc000422700)
/root/project/hugo/hugolib/hugo_sites.go:753 +0x8b
github(dot)com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc0005286e0, 0xc0000d12c0, 0x3132f38, 0x1)
/root/project/hugo/hugolib/hugo_sites_build.go:314 +0x1d3
github(dot)com/gohugoio/hugo/hugolib.(*HugoSites).Build.func4()
/root/project/hugo/hugolib/hugo_sites_build.go:149 +0x43
runtime/trace.WithRegion(0x24076c0, 0xc0004db080, 0x1e6a542, 0x6, 0xc000721e60)
/usr/local/go/src/runtime/trace/annotation.go:137 +0x105
github(dot)com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc0005286e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, …)
/root/project/hugo/hugolib/hugo_sites_build.go:151 +0x7bc
github(dot)com/gohugoio/hugo/commands.(*commandeer).buildSites(…)
/root/project/hugo/commands/hugo.go:703
github(dot)com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3(0xc0005e6058, 0x0)
/root/project/hugo/commands/hugo.go:315 +0x9d
golang(dot)org/x/sync/errgroup.(*Group).Go.func1(0xc0004db050, 0xc00059d790)
/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x60
created by golang(dot)org/x/sync/errgroup.(*Group).Go
/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x6d

**Comment by magoley** [comment]
OK I found it myself I had a problem with shortcodes... but still I need some help with the listing of elements for the taxonomy terms. This doesn't seem to be working for me.

**Comment by magoley** [comment]
is there a specific documentation on how you guys handle this in your theme?

**Comment by Somrat37** [comment]
There is no specific documentation. please tell me how can I help you?

**Comment by Somrat37** [comment]
I am going to close this issue, if you face any more issues, please create a new issue.
