### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by thcerit** [themefisher/liva-hugo#22]
Hi,

I can't deploy web site with this theme. Hugo version is 0.69. I tested with 0.68.3 and get same error.

Any suggestions?

root@srv01:~/cdn# hugo -d /home/admin/web/.../public_html/
Total in 120 ms
Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache

Best regards

**Comment by magoley** [comment]
Did you use the extended Hugo version?
This is needed due to SCSS.  Your error messsage heads to the same direction.
Hope that helps.
C

**Comment by thcerit** [comment]
@magoley thank you, extended version of Hugo build the theme successfuly.

Have a nice day :)

**Comment by javajon** [comment]
It will help others if on the [main page https://themes.gohugo.io/airspace-hugo/](https://themes.gohugo.io/airspace-hugo/) the version requirement is changed from

> Minimum Hugo Version: 0.64.0

to 

> Minimum Hugo Version: 0.64.0 **Extended**
