### ISSUE TITLE
type="post" not working.

### ISSUE THREAD

**Issue by KushajveerSingh** [themefisher/liva-hugo#24]
I created a new menu option in `config.toml` as follows
```
[[menu.main]]
  name = "Projects"
  URL = "projects"
  weight = 3
```

After this I created `_index.md` file `hugo new projects/_index.md`.

I have the following code in the file
```
---
title: "Projects"
date: 2020-05-13T02:37:23+05:30
draft: false
type: "post"
---
```

But this not work. It does not display the text in the page. But when I change to `type='about` it works. Am I setting the type wrong?

**Comment by Somrat37** [comment]
type: "post" is only for blog posts. you don't need to declare any type for creating a new page like this. but you need to create a layout for this page. you can copy the about page layout and rename it `projects`. and do some modifications.
