### ISSUE TITLE
Impossible to set content author

### ISSUE THREAD

**Issue by yinonov** [themefisher/liva-hugo#26]
I'm trying to set name of author in frontmatters but it seems that author is only fetched from site params `{{ .Site.Params.Author }}`

is there any way to override this in content pages?

**Comment by Somrat37** [comment]
Yes, you can do it.  make it `{{ .Params.Author }}` and set an `author` in post frontmattes.

**Comment by yinonov** [comment]
That means editing the theme’s code, which will harden the possibility for future updates of the sub module

**Comment by somrat-gyver** [comment]
Hey there, I have added this feature. now you don't have to edit the theme's code.
