### ISSUE TITLE
How to add home button on nav?

### ISSUE THREAD

**Issue by kucw** [themefisher/liva-hugo#28]
Due to the code changes, the home button is missing from the top-right corner nav. How can we put it back? It's really useful for our team members to get back to home page while viewing posts. Thanks!

**Comment by somrat-gyver** [comment]
# main menu
  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 3
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

**Comment by kucw** [comment]
It works, thanks!
