### ISSUE TITLE
How to add related content?

### ISSUE THREAD

**Issue by ashishmondal** [themefisher/liva-hugo#29]
I am trying to add related content in single.html by following this: https://gohugo.io/content-management/related/.

I am getting the following error:

ERROR 2020/07/12 02:39:28 Failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:43:11: executing "main" at <partial "related">: error calling partial: "C:\Users\hb75729\src\the-blissful-aura\layouts\partials\related.html:3:50": execute of template failed: template: partials/related.html:3:50: executing "partials/related.html" at <first (.Site.Params.relatedPostsNumber | default 5)>: error calling first: both limit and seq must be provided

**Comment by developer-evan** [comment]
Use a number after `first`, here `first 3 (.Site.Params.relatedPostsNumber | default 5)`

**Comment by ashishmondal** [comment]
I changed the first line to 

```
{{ $related := .Site.RegularPages.Related . | first 3 (.Site.Params.relatedPostsNumber | default 5) }}
```
Now I am getting the following error:

ERROR 2020/07/13 11:48:57 Failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:43:11: executing "main" at <partial "related">: error calling partial: "C:\Users\hb75729\src\the-blissful-aura\layouts\partials\related.html:3:50": execute of template failed: template: partials/related.html:3:50: executing "partials/related.html" at <first>: wrong number of args for first: want 2 got 3

**Comment by ashishmondal** [comment]
My bad. I forgot to add a . while including the partial. It's working now. Thanks.
