### ISSUE TITLE
How to enable several features?

### ISSUE THREAD

**Issue by nchelaru** [themefisher/liva-hugo#3]
Hello!

Liva is a great theme! :)

I am using this theme with a Blogdown site, if that is important for anything. 

I have been able to use the theme without problem, but several features do not seem to work out of the box:

- The search box leads to a "This site can’t be reached" error page
- The Contact page email box does not send email
- The Newsletter feature does not link up with anything

How can I set up these functionalities?

Thank you very much!

**Comment by Somrat37** [comment]
@nchelaru 

First: the search box should work, can you give me live url, so i can find your issue.
Second: the contact page will work with formspree.io, go to layout/contact/list.html. and replace form action with yours.
Third: the newsletter is not linkedup, you need to link it up, which service you want to use.

**Comment by nchelaru** [comment]
Thank you very much for your quick reply!

1. I have deployed the site and the search is working now
2. I got the contact page set up with formspree.io as instructed and it is working
3. I would like to use [Mailer Lite](https://www.mailerlite.com/) for the newsletter, please let me know how to set it up

**Comment by Somrat37** [comment]
Check this video tutorials : https://www.mailerlite.com/video-tutorials/quick-overview
