### ISSUE TITLE
Cloned and executed hugo server and didn't work

### ISSUE THREAD

**Issue by ricardopt** [themefisher/liva-hugo#33]
Hello,

Just followed your installation suggestion and ran `hugo server` on the main folder and also on the exampleSite and it didn't work.

Can you clarify this part?

Best regards,

**Comment by developer-evan** [comment]
hello @ricardopt ,

Please follow this doc to run this theme locally https://docs.gethugothemes.com/guide/#run-theme-locally

**Comment by developer-evan** [comment]
Hi @ricardopt 
I am going to close this issue, If you have any query to ask, feel free to re-open it, or create a new issue.
