### ISSUE TITLE
Post images flow out of the content

### ISSUE THREAD

**Issue by abskmj** [themefisher/liva-hugo#34]
Images added to the post by below markdown flow out of the content. Ideally, the images should remain within the content similar to the cover image. 

```
![photo](photo.jpeg)
```
![image](https://user-images.githubusercontent.com/29548356/97742767-c0035980-1b0a-11eb-9648-725bf96ad0b8.png)

**Comment by developer-evan** [comment]
Hello @abskmj 
Thanks for your concern. I Fixed this issue, now you can download the latest code. 

Also if you like this theme, please consider giving a star on the repository. thank you.

**Comment by abskmj** [comment]
Thank you @developer-evan, it works!
