### ISSUE TITLE
Two viewport meta tags in head.html

### ISSUE THREAD

**Issue by Frank3K** [themefisher/liva-hugo#9]
In `head.html` there are two viewport meta tags. Is this on purpose or is it a copy/past mistake?

```html
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
```

**Comment by Somrat37** [comment]
Those view port comes from bootstrap syntax, not a copy and not a mistake.

**Comment by Somrat37** [comment]
This issue has been fixed
